//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste1NFSE.NFSe {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", ConfigurationName="NFSe.LoteNFeSoap")]
    public interface LoteNFeSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (EnvioRPSRequest) da mensagem EnvioRPSRequest não corresponde ao valor padrão (EnvioRPS)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioRPS", ReplyAction="*")]
        Teste1NFSE.NFSe.EnvioRPSResponse EnvioRPS(Teste1NFSE.NFSe.EnvioRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.EnvioRPSResponse> EnvioRPSAsync(Teste1NFSE.NFSe.EnvioRPSRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (EnvioLoteRPSRequest) da mensagem EnvioLoteRPSRequest não corresponde ao valor padrão (EnvioLoteRPS)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPS", ReplyAction="*")]
        Teste1NFSE.NFSe.EnvioLoteRPSResponse EnvioLoteRPS(Teste1NFSE.NFSe.EnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.EnvioLoteRPSResponse> EnvioLoteRPSAsync(Teste1NFSE.NFSe.EnvioLoteRPSRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (TesteEnvioLoteRPSRequest) da mensagem TesteEnvioLoteRPSRequest não corresponde ao valor padrão (TesteEnvioLoteRPS)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/testeenvio", ReplyAction="*")]
        Teste1NFSE.NFSe.TesteEnvioLoteRPSResponse TesteEnvioLoteRPS(Teste1NFSE.NFSe.TesteEnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/testeenvio", ReplyAction="*")]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(Teste1NFSE.NFSe.TesteEnvioLoteRPSRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (CancelamentoNFeRequest) da mensagem CancelamentoNFeRequest não corresponde ao valor padrão (CancelamentoNFe)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/cancelamentoNFe", ReplyAction="*")]
        Teste1NFSE.NFSe.CancelamentoNFeResponse CancelamentoNFe(Teste1NFSE.NFSe.CancelamentoNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/cancelamentoNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.CancelamentoNFeResponse> CancelamentoNFeAsync(Teste1NFSE.NFSe.CancelamentoNFeRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultaNFeRequest) da mensagem ConsultaNFeRequest não corresponde ao valor padrão (ConsultaNFe)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFe", ReplyAction="*")]
        Teste1NFSE.NFSe.ConsultaNFeResponse ConsultaNFe(Teste1NFSE.NFSe.ConsultaNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaNFeResponse> ConsultaNFeAsync(Teste1NFSE.NFSe.ConsultaNFeRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultaNFeRecebidasRequest) da mensagem ConsultaNFeRecebidasRequest não corresponde ao valor padrão (ConsultaNFeRecebidas)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeRecebidas", ReplyAction="*")]
        Teste1NFSE.NFSe.ConsultaNFeRecebidasResponse ConsultaNFeRecebidas(Teste1NFSE.NFSe.ConsultaNFeRecebidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeRecebidas", ReplyAction="*")]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(Teste1NFSE.NFSe.ConsultaNFeRecebidasRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultaNFeEmitidasRequest) da mensagem ConsultaNFeEmitidasRequest não corresponde ao valor padrão (ConsultaNFeEmitidas)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeEmitidas", ReplyAction="*")]
        Teste1NFSE.NFSe.ConsultaNFeEmitidasResponse ConsultaNFeEmitidas(Teste1NFSE.NFSe.ConsultaNFeEmitidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeEmitidas", ReplyAction="*")]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(Teste1NFSE.NFSe.ConsultaNFeEmitidasRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultaLoteRequest) da mensagem ConsultaLoteRequest não corresponde ao valor padrão (ConsultaLote)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaLote", ReplyAction="*")]
        Teste1NFSE.NFSe.ConsultaLoteResponse ConsultaLote(Teste1NFSE.NFSe.ConsultaLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaLote", ReplyAction="*")]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaLoteResponse> ConsultaLoteAsync(Teste1NFSE.NFSe.ConsultaLoteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultaInformacoesLoteRequest) da mensagem ConsultaInformacoesLoteRequest não corresponde ao valor padrão (ConsultaInformacoesLote)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaInformacoesLote", ReplyAction="*")]
        Teste1NFSE.NFSe.ConsultaInformacoesLoteResponse ConsultaInformacoesLote(Teste1NFSE.NFSe.ConsultaInformacoesLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaInformacoesLote", ReplyAction="*")]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(Teste1NFSE.NFSe.ConsultaInformacoesLoteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultaCNPJRequest) da mensagem ConsultaCNPJRequest não corresponde ao valor padrão (ConsultaCNPJ)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaCNPJ", ReplyAction="*")]
        Teste1NFSE.NFSe.ConsultaCNPJResponse ConsultaCNPJ(Teste1NFSE.NFSe.ConsultaCNPJRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaCNPJ", ReplyAction="*")]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaCNPJResponse> ConsultaCNPJAsync(Teste1NFSE.NFSe.ConsultaCNPJRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioRPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public EnvioRPSRequest() {
        }
        
        public EnvioRPSRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioRPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public EnvioRPSResponse() {
        }
        
        public EnvioRPSResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioLoteRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioLoteRPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public EnvioLoteRPSRequest() {
        }
        
        public EnvioLoteRPSRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioLoteRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioLoteRPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public EnvioLoteRPSResponse() {
        }
        
        public EnvioLoteRPSResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TesteEnvioLoteRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class TesteEnvioLoteRPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public TesteEnvioLoteRPSRequest() {
        }
        
        public TesteEnvioLoteRPSRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TesteEnvioLoteRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class TesteEnvioLoteRPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public TesteEnvioLoteRPSResponse() {
        }
        
        public TesteEnvioLoteRPSResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelamentoNFeRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class CancelamentoNFeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public CancelamentoNFeRequest() {
        }
        
        public CancelamentoNFeRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelamentoNFeResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class CancelamentoNFeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public CancelamentoNFeResponse() {
        }
        
        public CancelamentoNFeResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRequest() {
        }
        
        public ConsultaNFeRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeResponse() {
        }
        
        public ConsultaNFeResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRecebidasRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRecebidasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRecebidasRequest() {
        }
        
        public ConsultaNFeRecebidasRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRecebidasResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRecebidasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeRecebidasResponse() {
        }
        
        public ConsultaNFeRecebidasResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeEmitidasRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeEmitidasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeEmitidasRequest() {
        }
        
        public ConsultaNFeEmitidasRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeEmitidasResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeEmitidasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeEmitidasResponse() {
        }
        
        public ConsultaNFeEmitidasResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLoteRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaLoteRequest() {
        }
        
        public ConsultaLoteRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLoteResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaLoteResponse() {
        }
        
        public ConsultaLoteResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacoesLoteRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaInformacoesLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaInformacoesLoteRequest() {
        }
        
        public ConsultaInformacoesLoteRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacoesLoteResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaInformacoesLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaInformacoesLoteResponse() {
        }
        
        public ConsultaInformacoesLoteResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCNPJRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaCNPJRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaCNPJRequest() {
        }
        
        public ConsultaCNPJRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCNPJResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaCNPJResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaCNPJResponse() {
        }
        
        public ConsultaCNPJResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoteNFeSoapChannel : Teste1NFSE.NFSe.LoteNFeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoteNFeSoapClient : System.ServiceModel.ClientBase<Teste1NFSE.NFSe.LoteNFeSoap>, Teste1NFSE.NFSe.LoteNFeSoap {
        
        public LoteNFeSoapClient() {
        }
        
        public LoteNFeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoteNFeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoteNFeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoteNFeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teste1NFSE.NFSe.EnvioRPSResponse Teste1NFSE.NFSe.LoteNFeSoap.EnvioRPS(Teste1NFSE.NFSe.EnvioRPSRequest request) {
            return base.Channel.EnvioRPS(request);
        }
        
        public string EnvioRPS(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.EnvioRPSRequest inValue = new Teste1NFSE.NFSe.EnvioRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Teste1NFSE.NFSe.EnvioRPSResponse retVal = ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).EnvioRPS(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.EnvioRPSResponse> Teste1NFSE.NFSe.LoteNFeSoap.EnvioRPSAsync(Teste1NFSE.NFSe.EnvioRPSRequest request) {
            return base.Channel.EnvioRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teste1NFSE.NFSe.EnvioRPSResponse> EnvioRPSAsync(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.EnvioRPSRequest inValue = new Teste1NFSE.NFSe.EnvioRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).EnvioRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teste1NFSE.NFSe.EnvioLoteRPSResponse Teste1NFSE.NFSe.LoteNFeSoap.EnvioLoteRPS(Teste1NFSE.NFSe.EnvioLoteRPSRequest request) {
            return base.Channel.EnvioLoteRPS(request);
        }
        
        public string EnvioLoteRPS(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.EnvioLoteRPSRequest inValue = new Teste1NFSE.NFSe.EnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Teste1NFSE.NFSe.EnvioLoteRPSResponse retVal = ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).EnvioLoteRPS(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.EnvioLoteRPSResponse> Teste1NFSE.NFSe.LoteNFeSoap.EnvioLoteRPSAsync(Teste1NFSE.NFSe.EnvioLoteRPSRequest request) {
            return base.Channel.EnvioLoteRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teste1NFSE.NFSe.EnvioLoteRPSResponse> EnvioLoteRPSAsync(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.EnvioLoteRPSRequest inValue = new Teste1NFSE.NFSe.EnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).EnvioLoteRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teste1NFSE.NFSe.TesteEnvioLoteRPSResponse Teste1NFSE.NFSe.LoteNFeSoap.TesteEnvioLoteRPS(Teste1NFSE.NFSe.TesteEnvioLoteRPSRequest request) {
            return base.Channel.TesteEnvioLoteRPS(request);
        }
        
        public string TesteEnvioLoteRPS(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.TesteEnvioLoteRPSRequest inValue = new Teste1NFSE.NFSe.TesteEnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Teste1NFSE.NFSe.TesteEnvioLoteRPSResponse retVal = ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).TesteEnvioLoteRPS(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.TesteEnvioLoteRPSResponse> Teste1NFSE.NFSe.LoteNFeSoap.TesteEnvioLoteRPSAsync(Teste1NFSE.NFSe.TesteEnvioLoteRPSRequest request) {
            return base.Channel.TesteEnvioLoteRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teste1NFSE.NFSe.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.TesteEnvioLoteRPSRequest inValue = new Teste1NFSE.NFSe.TesteEnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).TesteEnvioLoteRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teste1NFSE.NFSe.CancelamentoNFeResponse Teste1NFSE.NFSe.LoteNFeSoap.CancelamentoNFe(Teste1NFSE.NFSe.CancelamentoNFeRequest request) {
            return base.Channel.CancelamentoNFe(request);
        }
        
        public string CancelamentoNFe(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.CancelamentoNFeRequest inValue = new Teste1NFSE.NFSe.CancelamentoNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Teste1NFSE.NFSe.CancelamentoNFeResponse retVal = ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).CancelamentoNFe(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.CancelamentoNFeResponse> Teste1NFSE.NFSe.LoteNFeSoap.CancelamentoNFeAsync(Teste1NFSE.NFSe.CancelamentoNFeRequest request) {
            return base.Channel.CancelamentoNFeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teste1NFSE.NFSe.CancelamentoNFeResponse> CancelamentoNFeAsync(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.CancelamentoNFeRequest inValue = new Teste1NFSE.NFSe.CancelamentoNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).CancelamentoNFeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teste1NFSE.NFSe.ConsultaNFeResponse Teste1NFSE.NFSe.LoteNFeSoap.ConsultaNFe(Teste1NFSE.NFSe.ConsultaNFeRequest request) {
            return base.Channel.ConsultaNFe(request);
        }
        
        public string ConsultaNFe(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.ConsultaNFeRequest inValue = new Teste1NFSE.NFSe.ConsultaNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Teste1NFSE.NFSe.ConsultaNFeResponse retVal = ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).ConsultaNFe(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaNFeResponse> Teste1NFSE.NFSe.LoteNFeSoap.ConsultaNFeAsync(Teste1NFSE.NFSe.ConsultaNFeRequest request) {
            return base.Channel.ConsultaNFeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaNFeResponse> ConsultaNFeAsync(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.ConsultaNFeRequest inValue = new Teste1NFSE.NFSe.ConsultaNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).ConsultaNFeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teste1NFSE.NFSe.ConsultaNFeRecebidasResponse Teste1NFSE.NFSe.LoteNFeSoap.ConsultaNFeRecebidas(Teste1NFSE.NFSe.ConsultaNFeRecebidasRequest request) {
            return base.Channel.ConsultaNFeRecebidas(request);
        }
        
        public string ConsultaNFeRecebidas(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.ConsultaNFeRecebidasRequest inValue = new Teste1NFSE.NFSe.ConsultaNFeRecebidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Teste1NFSE.NFSe.ConsultaNFeRecebidasResponse retVal = ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).ConsultaNFeRecebidas(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaNFeRecebidasResponse> Teste1NFSE.NFSe.LoteNFeSoap.ConsultaNFeRecebidasAsync(Teste1NFSE.NFSe.ConsultaNFeRecebidasRequest request) {
            return base.Channel.ConsultaNFeRecebidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.ConsultaNFeRecebidasRequest inValue = new Teste1NFSE.NFSe.ConsultaNFeRecebidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).ConsultaNFeRecebidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teste1NFSE.NFSe.ConsultaNFeEmitidasResponse Teste1NFSE.NFSe.LoteNFeSoap.ConsultaNFeEmitidas(Teste1NFSE.NFSe.ConsultaNFeEmitidasRequest request) {
            return base.Channel.ConsultaNFeEmitidas(request);
        }
        
        public string ConsultaNFeEmitidas(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.ConsultaNFeEmitidasRequest inValue = new Teste1NFSE.NFSe.ConsultaNFeEmitidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Teste1NFSE.NFSe.ConsultaNFeEmitidasResponse retVal = ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).ConsultaNFeEmitidas(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaNFeEmitidasResponse> Teste1NFSE.NFSe.LoteNFeSoap.ConsultaNFeEmitidasAsync(Teste1NFSE.NFSe.ConsultaNFeEmitidasRequest request) {
            return base.Channel.ConsultaNFeEmitidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.ConsultaNFeEmitidasRequest inValue = new Teste1NFSE.NFSe.ConsultaNFeEmitidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).ConsultaNFeEmitidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teste1NFSE.NFSe.ConsultaLoteResponse Teste1NFSE.NFSe.LoteNFeSoap.ConsultaLote(Teste1NFSE.NFSe.ConsultaLoteRequest request) {
            return base.Channel.ConsultaLote(request);
        }
        
        public string ConsultaLote(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.ConsultaLoteRequest inValue = new Teste1NFSE.NFSe.ConsultaLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Teste1NFSE.NFSe.ConsultaLoteResponse retVal = ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).ConsultaLote(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaLoteResponse> Teste1NFSE.NFSe.LoteNFeSoap.ConsultaLoteAsync(Teste1NFSE.NFSe.ConsultaLoteRequest request) {
            return base.Channel.ConsultaLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaLoteResponse> ConsultaLoteAsync(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.ConsultaLoteRequest inValue = new Teste1NFSE.NFSe.ConsultaLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).ConsultaLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teste1NFSE.NFSe.ConsultaInformacoesLoteResponse Teste1NFSE.NFSe.LoteNFeSoap.ConsultaInformacoesLote(Teste1NFSE.NFSe.ConsultaInformacoesLoteRequest request) {
            return base.Channel.ConsultaInformacoesLote(request);
        }
        
        public string ConsultaInformacoesLote(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.ConsultaInformacoesLoteRequest inValue = new Teste1NFSE.NFSe.ConsultaInformacoesLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Teste1NFSE.NFSe.ConsultaInformacoesLoteResponse retVal = ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).ConsultaInformacoesLote(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaInformacoesLoteResponse> Teste1NFSE.NFSe.LoteNFeSoap.ConsultaInformacoesLoteAsync(Teste1NFSE.NFSe.ConsultaInformacoesLoteRequest request) {
            return base.Channel.ConsultaInformacoesLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.ConsultaInformacoesLoteRequest inValue = new Teste1NFSE.NFSe.ConsultaInformacoesLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).ConsultaInformacoesLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Teste1NFSE.NFSe.ConsultaCNPJResponse Teste1NFSE.NFSe.LoteNFeSoap.ConsultaCNPJ(Teste1NFSE.NFSe.ConsultaCNPJRequest request) {
            return base.Channel.ConsultaCNPJ(request);
        }
        
        public string ConsultaCNPJ(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.ConsultaCNPJRequest inValue = new Teste1NFSE.NFSe.ConsultaCNPJRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Teste1NFSE.NFSe.ConsultaCNPJResponse retVal = ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).ConsultaCNPJ(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaCNPJResponse> Teste1NFSE.NFSe.LoteNFeSoap.ConsultaCNPJAsync(Teste1NFSE.NFSe.ConsultaCNPJRequest request) {
            return base.Channel.ConsultaCNPJAsync(request);
        }
        
        public System.Threading.Tasks.Task<Teste1NFSE.NFSe.ConsultaCNPJResponse> ConsultaCNPJAsync(int VersaoSchema, string MensagemXML) {
            Teste1NFSE.NFSe.ConsultaCNPJRequest inValue = new Teste1NFSE.NFSe.ConsultaCNPJRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Teste1NFSE.NFSe.LoteNFeSoap)(this)).ConsultaCNPJAsync(inValue);
        }
    }
}
