'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.3038.
'
Namespace Nfe.Versao2.XmlModel.RetConsCad

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe"), _
     System.Xml.Serialization.XmlRootAttribute("retConsCad", [Namespace]:="http://www.portalfiscal.inf.br/nfe", IsNullable:=False)> _
    Partial Public Class TRetConsCad
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private infConsField As TRetConsCadInfCons

        Private versaoField As String

        '''<remarks/>
        Public Property infCons() As TRetConsCadInfCons
            Get
                Return Me.infConsField
            End Get
            Set(ByVal value As TRetConsCadInfCons)
                Me.infConsField = value
                Me.RaisePropertyChanged("infCons")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")> _
        Public Property versao() As String
            Get
                Return Me.versaoField
            End Get
            Set(ByVal value As String)
                Me.versaoField = value
                Me.RaisePropertyChanged("versao")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.portalfiscal.inf.br/nfe")> _
    Partial Public Class TRetConsCadInfCons
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private verAplicField As String

        Private cStatField As String

        Private xMotivoField As String

        Private ufField As TUfCons

        Private itemField As String

        Private itemElementNameField As ItemChoiceType

        Private dhConsField As Date

        Private cUFField As TCodUfIBGE

        Private infCadField() As TRetConsCadInfConsInfCad

        '''<remarks/>
        Public Property verAplic() As String
            Get
                Return Me.verAplicField
            End Get
            Set(ByVal value As String)
                Me.verAplicField = value
                Me.RaisePropertyChanged("verAplic")
            End Set
        End Property

        '''<remarks/>
        Public Property cStat() As String
            Get
                Return Me.cStatField
            End Get
            Set(ByVal value As String)
                Me.cStatField = value
                Me.RaisePropertyChanged("cStat")
            End Set
        End Property

        '''<remarks/>
        Public Property xMotivo() As String
            Get
                Return Me.xMotivoField
            End Get
            Set(ByVal value As String)
                Me.xMotivoField = value
                Me.RaisePropertyChanged("xMotivo")
            End Set
        End Property

        '''<remarks/>
        Public Property UF() As TUfCons
            Get
                Return Me.ufField
            End Get
            Set(ByVal value As TUfCons)
                Me.ufField = value
                Me.RaisePropertyChanged("UF")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CNPJ", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("CPF", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("IE", GetType(String)), _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")> _
        Public Property Item() As String
            Get
                Return Me.itemField
            End Get
            Set(ByVal value As String)
                Me.itemField = value
                Me.RaisePropertyChanged("Item")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ItemElementName() As ItemChoiceType
            Get
                Return Me.itemElementNameField
            End Get
            Set(ByVal value As ItemChoiceType)
                Me.itemElementNameField = value
                Me.RaisePropertyChanged("ItemElementName")
            End Set
        End Property

        '''<remarks/>
        Public Property dhCons() As Date
            Get
                Return Me.dhConsField
            End Get
            Set(ByVal value As Date)
                Me.dhConsField = value
                Me.RaisePropertyChanged("dhCons")
            End Set
        End Property

        '''<remarks/>
        Public Property cUF() As TCodUfIBGE
            Get
                Return Me.cUFField
            End Get
            Set(ByVal value As TCodUfIBGE)
                Me.cUFField = value
                Me.RaisePropertyChanged("cUF")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("infCad")> _
        Public Property infCad() As TRetConsCadInfConsInfCad()
            Get
                Return Me.infCadField
            End Get
            Set(ByVal value As TRetConsCadInfConsInfCad())
                Me.infCadField = value
                Me.RaisePropertyChanged("infCad")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe")> _
    Public Enum TUfCons

        '''<remarks/>
        AC

        '''<remarks/>
        AL

        '''<remarks/>
        AM

        '''<remarks/>
        AP

        '''<remarks/>
        BA

        '''<remarks/>
        CE

        '''<remarks/>
        DF

        '''<remarks/>
        ES

        '''<remarks/>
        GO

        '''<remarks/>
        MA

        '''<remarks/>
        MG

        '''<remarks/>
        MS

        '''<remarks/>
        MT

        '''<remarks/>
        PA

        '''<remarks/>
        PB

        '''<remarks/>
        PE

        '''<remarks/>
        PI

        '''<remarks/>
        PR

        '''<remarks/>
        RJ

        '''<remarks/>
        RN

        '''<remarks/>
        RO

        '''<remarks/>
        RR

        '''<remarks/>
        RS

        '''<remarks/>
        SC

        '''<remarks/>
        SE

        '''<remarks/>
        SP

        '''<remarks/>
        [TO]

        '''<remarks/>
        SU
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe", IncludeInSchema:=False)> _
    Public Enum ItemChoiceType

        '''<remarks/>
        CNPJ

        '''<remarks/>
        CPF

        '''<remarks/>
        IE
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe")> _
    Public Enum TCodUfIBGE

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("11")> _
        UF_RO = 11

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("12")> _
        UF_AC = 12

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("13")> _
        UF_AM = 13

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("14")> _
        UF_RR = 14

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("15")> _
        UF_PA = 15

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("16")> _
        UF_AP = 16

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("17")> _
        UF_TO = 17

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("21")> _
        UF_MA = 21

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("22")> _
        UF_PI = 22

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("23")> _
        UF_CE = 23

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("24")> _
        UF_RN = 24

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("25")> _
        UF_PB = 25

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("26")> _
        UF_PE = 26

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("27")> _
        UF_AL = 27

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("28")> _
        UF_SE = 28

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("29")> _
        UF_BA = 29

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("31")> _
        UF_MG = 31

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("32")> _
        UF_ES = 32

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("33")> _
        UF_RJ = 33

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("35")> _
        UF_SP = 35

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("41")> _
        UF_PR = 41

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("42")> _
        UF_SC = 42

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("43")> _
        UF_RS = 43

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("50")> _
        UF_MS = 50

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("51")> _
        UF_MT = 51

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("52")> _
        UF_GO = 52

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("53")> _
        UF_DF = 53

    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.portalfiscal.inf.br/nfe")> _
    Partial Public Class TRetConsCadInfConsInfCad
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private ieField As String

        Private itemField As String

        Private itemElementNameField As ItemChoiceType1

        Private ufField As TUf

        Private cSitField As TRetConsCadInfConsInfCadCSit

        Private indCredNFeField As TRetConsCadInfConsInfCadIndCredNFe

        Private indCredCTeField As TRetConsCadInfConsInfCadIndCredCTe

        Private xNomeField As String

        Private xFantField As String

        Private xRegApurField As String

        Private cNAEField As String

        Private dIniAtivField As Date

        Private dIniAtivFieldSpecified As Boolean

        Private dUltSitField As Date

        Private dUltSitFieldSpecified As Boolean

        Private dBaixaField As Date

        Private dBaixaFieldSpecified As Boolean

        Private iEUnicaField As String

        Private iEAtualField As String

        Private enderField As TEndereco

        '''<remarks/>
        Public Property IE() As String
            Get
                Return Me.ieField
            End Get
            Set(ByVal value As String)
                Me.ieField = value
                Me.RaisePropertyChanged("IE")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CNPJ", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("CPF", GetType(String)), _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")> _
        Public Property Item() As String
            Get
                Return Me.itemField
            End Get
            Set(ByVal value As String)
                Me.itemField = value
                Me.RaisePropertyChanged("Item")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ItemElementName() As ItemChoiceType1
            Get
                Return Me.itemElementNameField
            End Get
            Set(ByVal value As ItemChoiceType1)
                Me.itemElementNameField = value
                Me.RaisePropertyChanged("ItemElementName")
            End Set
        End Property

        '''<remarks/>
        Public Property UF() As TUf
            Get
                Return Me.ufField
            End Get
            Set(ByVal value As TUf)
                Me.ufField = value
                Me.RaisePropertyChanged("UF")
            End Set
        End Property

        '''<remarks/>
        Public Property cSit() As TRetConsCadInfConsInfCadCSit
            Get
                Return Me.cSitField
            End Get
            Set(ByVal value As TRetConsCadInfConsInfCadCSit)
                Me.cSitField = value
                Me.RaisePropertyChanged("cSit")
            End Set
        End Property

        '''<remarks/>
        Public Property indCredNFe() As TRetConsCadInfConsInfCadIndCredNFe
            Get
                Return Me.indCredNFeField
            End Get
            Set(ByVal value As TRetConsCadInfConsInfCadIndCredNFe)
                Me.indCredNFeField = value
                Me.RaisePropertyChanged("indCredNFe")
            End Set
        End Property

        '''<remarks/>
        Public Property indCredCTe() As TRetConsCadInfConsInfCadIndCredCTe
            Get
                Return Me.indCredCTeField
            End Get
            Set(ByVal value As TRetConsCadInfConsInfCadIndCredCTe)
                Me.indCredCTeField = value
                Me.RaisePropertyChanged("indCredCTe")
            End Set
        End Property

        '''<remarks/>
        Public Property xNome() As String
            Get
                Return Me.xNomeField
            End Get
            Set(ByVal value As String)
                Me.xNomeField = value
                Me.RaisePropertyChanged("xNome")
            End Set
        End Property

        '''<remarks/>
        Public Property xFant() As String
            Get
                Return Me.xFantField
            End Get
            Set(ByVal value As String)
                Me.xFantField = value
                Me.RaisePropertyChanged("xFant")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token")> _
        Public Property xRegApur() As String
            Get
                Return Me.xRegApurField
            End Get
            Set(ByVal value As String)
                Me.xRegApurField = value
                Me.RaisePropertyChanged("xRegApur")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token")> _
        Public Property CNAE() As String
            Get
                Return Me.cNAEField
            End Get
            Set(ByVal value As String)
                Me.cNAEField = value
                Me.RaisePropertyChanged("CNAE")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property dIniAtiv() As Date
            Get
                Return Me.dIniAtivField
            End Get
            Set(ByVal value As Date)
                Me.dIniAtivField = value
                Me.RaisePropertyChanged("dIniAtiv")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property dIniAtivSpecified() As Boolean
            Get
                Return Me.dIniAtivFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dIniAtivFieldSpecified = value
                Me.RaisePropertyChanged("dIniAtivSpecified")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property dUltSit() As Date
            Get
                Return Me.dUltSitField
            End Get
            Set(ByVal value As Date)
                Me.dUltSitField = value
                Me.RaisePropertyChanged("dUltSit")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property dUltSitSpecified() As Boolean
            Get
                Return Me.dUltSitFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dUltSitFieldSpecified = value
                Me.RaisePropertyChanged("dUltSitSpecified")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property dBaixa() As Date
            Get
                Return Me.dBaixaField
            End Get
            Set(ByVal value As Date)
                Me.dBaixaField = value
                Me.RaisePropertyChanged("dBaixa")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property dBaixaSpecified() As Boolean
            Get
                Return Me.dBaixaFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.dBaixaFieldSpecified = value
                Me.RaisePropertyChanged("dBaixaSpecified")
            End Set
        End Property

        '''<remarks/>
        Public Property IEUnica() As String
            Get
                Return Me.iEUnicaField
            End Get
            Set(ByVal value As String)
                Me.iEUnicaField = value
                Me.RaisePropertyChanged("IEUnica")
            End Set
        End Property

        '''<remarks/>
        Public Property IEAtual() As String
            Get
                Return Me.iEAtualField
            End Get
            Set(ByVal value As String)
                Me.iEAtualField = value
                Me.RaisePropertyChanged("IEAtual")
            End Set
        End Property

        '''<remarks/>
        Public Property ender() As TEndereco
            Get
                Return Me.enderField
            End Get
            Set(ByVal value As TEndereco)
                Me.enderField = value
                Me.RaisePropertyChanged("ender")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe", IncludeInSchema:=False)> _
    Public Enum ItemChoiceType1

        '''<remarks/>
        CNPJ

        '''<remarks/>
        CPF
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe")> _
    Public Enum TUf

        '''<remarks/>
        AC

        '''<remarks/>
        AL

        '''<remarks/>
        AM

        '''<remarks/>
        AP

        '''<remarks/>
        BA

        '''<remarks/>
        CE

        '''<remarks/>
        DF

        '''<remarks/>
        ES

        '''<remarks/>
        GO

        '''<remarks/>
        MA

        '''<remarks/>
        MG

        '''<remarks/>
        MS

        '''<remarks/>
        MT

        '''<remarks/>
        PA

        '''<remarks/>
        PB

        '''<remarks/>
        PE

        '''<remarks/>
        PI

        '''<remarks/>
        PR

        '''<remarks/>
        RJ

        '''<remarks/>
        RN

        '''<remarks/>
        RO

        '''<remarks/>
        RR

        '''<remarks/>
        RS

        '''<remarks/>
        SC

        '''<remarks/>
        SE

        '''<remarks/>
        SP

        '''<remarks/>
        [TO]

        '''<remarks/>
        EX
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.portalfiscal.inf.br/nfe")> _
    Public Enum TRetConsCadInfConsInfCadCSit

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("0")> _
        Item0

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1")> _
        Item1
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.portalfiscal.inf.br/nfe")> _
    Public Enum TRetConsCadInfConsInfCadIndCredNFe

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("0")> _
        Item0

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1")> _
        Item1

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2")> _
        Item2

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("3")> _
        Item3

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("4")> _
        Item4
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.portalfiscal.inf.br/nfe")> _
    Public Enum TRetConsCadInfConsInfCadIndCredCTe

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("0")> _
        Item0

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1")> _
        Item1

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2")> _
        Item2

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("3")> _
        Item3

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("4")> _
        Item4
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe")> _
    Partial Public Class TEndereco
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private xLgrField As String

        Private nroField As String

        Private xCplField As String

        Private xBairroField As String

        Private cMunField As String

        Private xMunField As String

        Private cEPField As String

        '''<remarks/>
        Public Property xLgr() As String
            Get
                Return Me.xLgrField
            End Get
            Set(ByVal value As String)
                Me.xLgrField = value
                Me.RaisePropertyChanged("xLgr")
            End Set
        End Property

        '''<remarks/>
        Public Property nro() As String
            Get
                Return Me.nroField
            End Get
            Set(ByVal value As String)
                Me.nroField = value
                Me.RaisePropertyChanged("nro")
            End Set
        End Property

        '''<remarks/>
        Public Property xCpl() As String
            Get
                Return Me.xCplField
            End Get
            Set(ByVal value As String)
                Me.xCplField = value
                Me.RaisePropertyChanged("xCpl")
            End Set
        End Property

        '''<remarks/>
        Public Property xBairro() As String
            Get
                Return Me.xBairroField
            End Get
            Set(ByVal value As String)
                Me.xBairroField = value
                Me.RaisePropertyChanged("xBairro")
            End Set
        End Property

        '''<remarks/>
        Public Property cMun() As String
            Get
                Return Me.cMunField
            End Get
            Set(ByVal value As String)
                Me.cMunField = value
                Me.RaisePropertyChanged("cMun")
            End Set
        End Property

        '''<remarks/>
        Public Property xMun() As String
            Get
                Return Me.xMunField
            End Get
            Set(ByVal value As String)
                Me.xMunField = value
                Me.RaisePropertyChanged("xMun")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token")> _
        Public Property CEP() As String
            Get
                Return Me.cEPField
            End Get
            Set(ByVal value As String)
                Me.cEPField = value
                Me.RaisePropertyChanged("CEP")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("Signature", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class SignatureType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private signedInfoField As SignedInfoType

        Private signatureValueField As SignatureValueType

        Private keyInfoField As KeyInfoType

        Private idField As String

        '''<remarks/>
        Public Property SignedInfo() As SignedInfoType
            Get
                Return Me.signedInfoField
            End Get
            Set(ByVal value As SignedInfoType)
                Me.signedInfoField = value
                Me.RaisePropertyChanged("SignedInfo")
            End Set
        End Property

        '''<remarks/>
        Public Property SignatureValue() As SignatureValueType
            Get
                Return Me.signatureValueField
            End Get
            Set(ByVal value As SignatureValueType)
                Me.signatureValueField = value
                Me.RaisePropertyChanged("SignatureValue")
            End Set
        End Property

        '''<remarks/>
        Public Property KeyInfo() As KeyInfoType
            Get
                Return Me.keyInfoField
            End Get
            Set(ByVal value As KeyInfoType)
                Me.keyInfoField = value
                Me.RaisePropertyChanged("KeyInfo")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
    Partial Public Class SignedInfoType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private canonicalizationMethodField As SignedInfoTypeCanonicalizationMethod

        Private signatureMethodField As SignedInfoTypeSignatureMethod

        Private referenceField As ReferenceType

        Private idField As String

        '''<remarks/>
        Public Property CanonicalizationMethod() As SignedInfoTypeCanonicalizationMethod
            Get
                Return Me.canonicalizationMethodField
            End Get
            Set(ByVal value As SignedInfoTypeCanonicalizationMethod)
                Me.canonicalizationMethodField = value
                Me.RaisePropertyChanged("CanonicalizationMethod")
            End Set
        End Property

        '''<remarks/>
        Public Property SignatureMethod() As SignedInfoTypeSignatureMethod
            Get
                Return Me.signatureMethodField
            End Get
            Set(ByVal value As SignedInfoTypeSignatureMethod)
                Me.signatureMethodField = value
                Me.RaisePropertyChanged("SignatureMethod")
            End Set
        End Property

        '''<remarks/>
        Public Property Reference() As ReferenceType
            Get
                Return Me.referenceField
            End Get
            Set(ByVal value As ReferenceType)
                Me.referenceField = value
                Me.RaisePropertyChanged("Reference")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
    Partial Public Class SignedInfoTypeCanonicalizationMethod
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private algorithmField As String

        Public Sub New()
            MyBase.New()
            Me.algorithmField = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315"
        End Sub

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set(ByVal value As String)
                Me.algorithmField = value
                Me.RaisePropertyChanged("Algorithm")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
    Partial Public Class SignedInfoTypeSignatureMethod
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private algorithmField As String

        Public Sub New()
            MyBase.New()
            Me.algorithmField = "http://www.w3.org/2000/09/xmldsig#rsa-sha1"
        End Sub

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set(ByVal value As String)
                Me.algorithmField = value
                Me.RaisePropertyChanged("Algorithm")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
    Partial Public Class ReferenceType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private transformsField() As TransformType

        Private digestMethodField As ReferenceTypeDigestMethod

        Private digestValueField() As Byte

        Private idField As String

        Private uRIField As String

        Private typeField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=False)> _
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set(ByVal value As TransformType())
                Me.transformsField = value
                Me.RaisePropertyChanged("Transforms")
            End Set
        End Property

        '''<remarks/>
        Public Property DigestMethod() As ReferenceTypeDigestMethod
            Get
                Return Me.digestMethodField
            End Get
            Set(ByVal value As ReferenceTypeDigestMethod)
                Me.digestMethodField = value
                Me.RaisePropertyChanged("DigestMethod")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property DigestValue() As Byte()
            Get
                Return Me.digestValueField
            End Get
            Set(ByVal value As Byte())
                Me.digestValueField = value
                Me.RaisePropertyChanged("DigestValue")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set(ByVal value As String)
                Me.uRIField = value
                Me.RaisePropertyChanged("URI")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set(ByVal value As String)
                Me.typeField = value
                Me.RaisePropertyChanged("Type")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
    Partial Public Class TransformType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private xPathField() As String

        Private algorithmField As TTransformURI

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("XPath")> _
        Public Property XPath() As String()
            Get
                Return Me.xPathField
            End Get
            Set(ByVal value As String())
                Me.xPathField = value
                Me.RaisePropertyChanged("XPath")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Algorithm() As TTransformURI
            Get
                Return Me.algorithmField
            End Get
            Set(ByVal value As TTransformURI)
                Me.algorithmField = value
                Me.RaisePropertyChanged("Algorithm")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
    Public Enum TTransformURI

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#enveloped-signature")> _
        httpwwww3org200009xmldsigenvelopedsignature

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/TR/2001/REC-xml-c14n-20010315")> _
        httpwwww3orgTR2001RECxmlc14n20010315
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
    Partial Public Class ReferenceTypeDigestMethod
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private algorithmField As String

        Public Sub New()
            MyBase.New()
            Me.algorithmField = "http://www.w3.org/2000/09/xmldsig#sha1"
        End Sub

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set(ByVal value As String)
                Me.algorithmField = value
                Me.RaisePropertyChanged("Algorithm")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
    Partial Public Class SignatureValueType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private idField As String

        Private valueField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="base64Binary")> _
        Public Property Value() As Byte()
            Get
                Return Me.valueField
            End Get
            Set(ByVal value As Byte())
                Me.valueField = value
                Me.RaisePropertyChanged("Value")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
    Partial Public Class KeyInfoType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private x509DataField As X509DataType

        Private idField As String

        '''<remarks/>
        Public Property X509Data() As X509DataType
            Get
                Return Me.x509DataField
            End Get
            Set(ByVal value As X509DataType)
                Me.x509DataField = value
                Me.RaisePropertyChanged("X509Data")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
    Partial Public Class X509DataType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private x509CertificateField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property X509Certificate() As Byte()
            Get
                Return Me.x509CertificateField
            End Get
            Set(ByVal value As Byte())
                Me.x509CertificateField = value
                Me.RaisePropertyChanged("X509Certificate")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
End Namespace
