'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.7.2053.0.
'
Namespace Cte.Versao1.XmlModel.RetDistDFeInt


    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.portalfiscal.inf.br/cte"),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.portalfiscal.inf.br/cte", IsNullable:=False)>
    Partial Public Class retDistDFeInt

        Private tpAmbField As TAmb

        Private verAplicField As String

        Private cStatField As String

        Private xMotivoField As String

        Private dhRespField As String

        Private ultNSUField As String

        Private maxNSUField As String

        Private loteDistDFeIntField As retDistDFeIntLoteDistDFeInt

        Private versaoField As TVerDistDFe

        '''<remarks/>
        Public Property tpAmb() As TAmb
            Get
                Return Me.tpAmbField
            End Get
            Set
                Me.tpAmbField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property verAplic() As String
            Get
                Return Me.verAplicField
            End Get
            Set
                Me.verAplicField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property cStat() As String
            Get
                Return Me.cStatField
            End Get
            Set
                Me.cStatField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property xMotivo() As String
            Get
                Return Me.xMotivoField
            End Get
            Set
                Me.xMotivoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property dhResp() As String
            Get
                Return Me.dhRespField
            End Get
            Set
                Me.dhRespField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token")>
        Public Property ultNSU() As String
            Get
                Return Me.ultNSUField
            End Get
            Set
                Me.ultNSUField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token")>
        Public Property maxNSU() As String
            Get
                Return Me.maxNSUField
            End Get
            Set
                Me.maxNSUField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property loteDistDFeInt() As retDistDFeIntLoteDistDFeInt
            Get
                Return Me.loteDistDFeIntField
            End Get
            Set
                Me.loteDistDFeIntField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property versao() As TVerDistDFe
            Get
                Return Me.versaoField
            End Get
            Set
                Me.versaoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/cte")>
    Public Enum TAmb

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1")>
        Item1

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2")>
        Item2
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.portalfiscal.inf.br/cte")>
    Partial Public Class retDistDFeIntLoteDistDFeInt

        Private docZipField() As retDistDFeIntLoteDistDFeIntDocZip

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("docZip")>
        Public Property docZip() As retDistDFeIntLoteDistDFeIntDocZip()
            Get
                Return Me.docZipField
            End Get
            Set
                Me.docZipField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.portalfiscal.inf.br/cte")>
    Partial Public Class retDistDFeIntLoteDistDFeIntDocZip

        Private nSUField As String

        Private schemaField As String

        Private valueField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>
        Public Property NSU() As String
            Get
                Return Me.nSUField
            End Get
            Set
                Me.nSUField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property schema() As String
            Get
                Return Me.schemaField
            End Get
            Set
                Me.schemaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="base64Binary")>
        Public Property Value() As Byte()
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/cte")>
    Public Enum TVerDistDFe

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1.00")>
        Item100
    End Enum

End Namespace