'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=4.7.2053.0.
'
Namespace Cte.Versao1.WSDL.DistribuicaoDFe
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2053.0"),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Web.Services.WebServiceBindingAttribute(Name:="CTeDistribuicaoDFeSoap", [Namespace]:="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe")>
    Partial Public Class CTeDistribuicaoDFe
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private cteDistDFeInteresseOperationCompleted As System.Threading.SendOrPostCallback

        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "https://www1.cte.fazenda.gov.br/CTeDistribuicaoDFe/CTeDistribuicaoDFe.asmx"
        End Sub

        '''<remarks/>
        Public Event cteDistDFeInteresseCompleted As cteDistDFeInteresseCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe/cteDistDFeInteresse", RequestNamespace:="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", ResponseNamespace:="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
        Public Function cteDistDFeInteresse(ByVal cteDadosMsg As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("cteDistDFeInteresse", New Object() {cteDadosMsg})
            Return CType(results(0), System.Xml.XmlNode)
        End Function

        '''<remarks/>
        Public Function BegincteDistDFeInteresse(ByVal cteDadosMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("cteDistDFeInteresse", New Object() {cteDadosMsg}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndcteDistDFeInteresse(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Xml.XmlNode)
        End Function

        '''<remarks/>
        Public Overloads Sub cteDistDFeInteresseAsync(ByVal cteDadosMsg As System.Xml.XmlNode)
            Me.cteDistDFeInteresseAsync(cteDadosMsg, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub cteDistDFeInteresseAsync(ByVal cteDadosMsg As System.Xml.XmlNode, ByVal userState As Object)
            If (Me.cteDistDFeInteresseOperationCompleted Is Nothing) Then
                Me.cteDistDFeInteresseOperationCompleted = AddressOf Me.OncteDistDFeInteresseOperationCompleted
            End If
            Me.InvokeAsync("cteDistDFeInteresse", New Object() {cteDadosMsg}, Me.cteDistDFeInteresseOperationCompleted, userState)
        End Sub

        Private Sub OncteDistDFeInteresseOperationCompleted(ByVal arg As Object)
            If (Not (Me.cteDistDFeInteresseCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cteDistDFeInteresseCompleted(Me, New cteDistDFeInteresseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2053.0")>
    Public Delegate Sub cteDistDFeInteresseCompletedEventHandler(ByVal sender As Object, ByVal e As cteDistDFeInteresseCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2053.0"),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class cteDistDFeInteresseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0), System.Xml.XmlNode)
            End Get
        End Property
    End Class
End Namespace
